build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "pip.exe install -r requirements.txt"
  - "pip.exe install pytest"

test_script:
  - "%PYTHON%/pytest.py"
